### ISSUE TITLE
switch trunk config does not work with mode change

### ISSUE THREAD

**Issue by HaroldYE** [fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection#6] opened 2023-07-13 20:58 UTC
[Problem Description]

when I implement the playbook below,  switch does not change the mode to lacp-active, it keeps in static and lacp speed does not change to fast, ansible tasks show change finished. and I put the result below as well

`---
- hosts: fortiswitch01
  collections:
  - fortinet.fortiswitch
  connection: httpapi
  gather_facts: 'no'
  vars:
    ansible_httpapi_use_ssl: 'yes'
    ansible_httpapi_validate_certs: 'no'
    ansible_httpapi_port: 443
  tasks:
   - name: Port 15
     fortiswitch_switch_trunk:
       state: "present"
       switch_trunk:
         name: "PC15"
         mode: 'lacp_active'
         description: "test"
         lacp_speed: "fast"
         members:
           - member_name: "port15"

  edit "PC15"
        set description "test"
        set members "port15"         
    next`
`

**Comment by MaxxLiu22** [comment] 2023-12-27 23:34
Hi @HaroldYE ,

Thank you for raising this question, and sorry for the late reply, I can reproduce this issue, I find in CLI ``mode`` could be set as ``lacp-active`` but Ansible only accepts ``lacp_active``, the sign difference may be the cause to this issue, I will let you know once that has been fixed.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment] 2024-05-30 23:03
Hi @HaroldYE ,

This issue has been fixed on fortinet.fortiswitch:1.2.3, I will go ahead to close this case, if you still have questions, feel free to reopen it or another case,

Thanks,
Maxx

**Closed by MaxxLiu22** 2024-05-30 23:03 UTC
